version: "3.9"

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-root}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  api:
    build: ./api
    container_name: monitor-clima-api
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - rabbitmq

  collector:
    build: ./collector
    container_name: monitor-clima-collector
    depends_on:
      - mongodb
      - rabbitmq

  worker:
    build: ./worker
    container_name: monitor-clima-worker
    depends_on:
      - mongodb
      - rabbitmq

volumes:
  mongodb_data: